{% set version = "0.5" %}
{% set sha256 = "4755c5da28eb692e12b6ef787e46f5386d76d580d4b6f1df149d8372a2367993" %}

package:
  name: multiphate 
  version: '{{ version }}' 

source:
  git_url: https://github.com/carolzhou/multiPhATEb.git/multiphate.tar.gz 
  sha256: '{{ sha256 }}' 

build:
  number: 1 
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.0
  run:
    - python >=3.0
    - biopython
    - tRNAscan-SE >=2.0
    - blast >=2.7.1
    - glimmer >=3.02
    - prodigal >=2.6
    - hmmer >=3.1b2
    - emboss >=6.6.0
    
test:
  commands:
    - tRNAscan-SE -h
    - blastp -version
    - prodigal -v
    - jackhmmer -h
    - transeq --version

about:
  home: https://github.com/carolzhou/multiPhATEb.git
  license: BSD-3
  license_family: BSD
  license_file: BSD-3.pdf
  summary: de novo annotation of phage genome sequence
  dev_url: https://github.com/carolzhou/multiPhATEb

extra:
  identifiers:
    - biotools:multiphate
    - doi:10.1101/551010

