{% set version = "0.5" %}
{% set sha256 = "f46af4d72461ed508b927075de2806c47b40407d" %}

package:
  name: multiphate 
  version: '{{ version }}' 

source:
  url: https://github.com/carolzhou/multiPhATEb/multiphate.tar.gz
  sha256: '{{ sha256 }}' 

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
  run:
    - python >=3.0
    - tRNAscan-SE >=2.0
    - emboss >=6.0
    - biopython
    - blast >=2.7.1
    - glimmer >=3.02
    - prodigal >=2.6
    - hmmer >=3.1b2

test:
  commands:
    - blastp -help
    - prodigal -h

about:
  home: https://github.com/carolzhou/multiPhATEb.git
  license: BSD-3
  license_family: BSD
  license_file: BSD-3.pdf
  summary: de novo annotation of phage genome sequence
  dev_url: https://github.com/carolzhou/multiPhATEb

extra:
  identifiers:
    - biotools:multiphate
