{% set version = "0.1.0" %}
{% set sha256 = "" %}

package:
  name: multiphate 
  version: '{{ version }}' 

source:
  url: https://github.com/carolzhou/multiPhATEb.git 
  sha256: '{{ sha256 }}' 

build:
  number: 1 
  noarch: python
  skip: True
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
  run:
    - python
    - biopython
    - trnascan-se
    - blast
    - glimmer3
    - prodigal
    - hmmer
    - emboss
    
test:
  commands:
    - trnascan-se -h
    - blastp -version
    - prodigal -v
    - jackhmmer -h
    - transeq --version
    - python -m multiphate usage

about:
  home: https://github.com/carolzhou/multiPhATEb.git
  license: BSD-3
  license_family: BSD
  license_file: BSD-3.pdf
  summary: de novo annotation of phage genome sequence
  dev_url: https://github.com/carolzhou/multiPhATEb

extra:
  identifiers:
    - biotools:multiphate
    - doi:10.1101/551010

