{% set version = "0.5" %}
{% set sha256 = "8b88c0d350d8b5b7a3046559874948bf56e6cc918eadba02106820f5ffcc0b29" %}

package:
  name: multiphate 
  version: '{{ version }}' 

source:
  url: https://github.com/carolzhou/multiPhATEb/blob/master/multiphate.tar.gz 
  sha256: '{{ sha256 }}' 

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - pip
    - biopython
    - tRNAscan-SE >=2.0
    - blast >=2.7.1
    - glimmer >=3.02
    - prodigal >=2.6
    - hmmer >=3.1b2
    - emboss >=6.6.0
    
test:
  commands:
    - tRNAscan-SE -h
    - blastp -version
    - prodigal -v
    - jackhmmer -h
    - transeq --version
    - multiPhate.py usage

about:
  home: https://github.com/carolzhou/multiPhATEb.git
  license: BSD-3
  license_family: BSD
  license_file: BSD-3.pdf
  summary: de novo annotation of phage genome sequence
  dev_url: https://github.com/carolzhou/multiPhATEb

extra:
  identifiers:
    - biotools:multiphate
    - doi:10.1101/551010

